encoding    : UTF-8
exclude     : [.idea]

title       : YouTube Geofind
subtitle    : Discover Geo-tagged Videos
author      : mattwright324
copyright   : Â© 2019 Matthew Wright
github      : https://github.com/mattwright324/
github_repo : https://github.com/mattwright324/youtube-geofind/
gh_pages    : https://mattw.io/youtube-geofind/